//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIDTERMPROJECT.Models.Dataase
{
    using System;
    using System.Collections.Generic;
    using System.Web;
    using System.Web.Mvc;

    public partial class Product
    {
        public int Id { get; set; }
        public string productName { get; set; }
        public string productPrice { get; set; }
        public string productImage { get; set; }
        public string productDescription { get; set; }
        public string productQuantity { get; set; }
        public int categoryId { get; set; }

        public SelectList CategoryList { get; set; }
        public HttpPostedFileBase ImageFiles { get; set; }

        public virtual Category Category { get; set; }
    }
}
